# Generated by Django 4.1.5 on 2023-01-30 17:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoneList",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=30)),
                ("startDate", models.DateField(verbose_name="%Y.%m.")),
                ("finishDate", models.DateField(verbose_name="%Y.%m.")),
                ("Whatis", models.CharField(max_length=2000)),
                ("Whatdid", models.CharField(max_length=2000)),
                ("Episode", models.CharField(max_length=2000)),
                ("Major", models.CharField(max_length=20)),
                ("Activity", models.CharField(max_length=20)),
                ("Colorcode", models.CharField(max_length=8)),
            ],
            options={"db_table": "DoneList",},
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "userId",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Nickname", models.CharField(max_length=20, unique=True)),
                ("Password", models.CharField(max_length=30)),
                (
                    "Year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1199),
                            django.core.validators.MaxValueValidator(2199),
                        ]
                    ),
                ),
            ],
            options={"db_table": "Member",},
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "doneId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.donelist"
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.member"
                    ),
                ),
            ],
            options={"db_table": "Like",},
        ),
        migrations.AddField(
            model_name="donelist",
            name="userId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.member"
            ),
        ),
        migrations.CreateModel(
            name="DM",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField(max_length=1000)),
                ("time", models.DateField(auto_now_add=True)),
                (
                    "doneId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.donelist"
                    ),
                ),
                (
                    "receiveId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receive",
                        to="main.member",
                    ),
                ),
                (
                    "sendId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send",
                        to="main.member",
                    ),
                ),
            ],
            options={"db_table": "DM",},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField(max_length=1000)),
                (
                    "doneId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.donelist"
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.member"
                    ),
                ),
            ],
            options={"db_table": "comment",},
        ),
    ]
