# Generated by Django 4.1.5 on 2023-02-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donelist",
            name="Episode",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="donelist",
            name="Whatdid",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="donelist",
            name="Whatis",
            field=models.TextField(max_length=2000),
        ),
    ]
